"""initial schema

Revision ID: 8284c14cf045
Revises: 
Create Date: 2026-09-04 21:59:14.221922
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '8284c14cf045'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('pincode', sa.String(length=12), nullable=False),
    sa.Column('signup_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('total_spend', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('return_count', sa.Integer(), nullable=False),
    sa.Column('rto_count', sa.Integer(), nullable=False),
    sa.Column('abandonment_count', sa.Integer(), nullable=False),
    sa.Column('delivery_failure_count', sa.Integer(), nullable=False),
    sa.Column('cod_refusal_count', sa.Integer(), nullable=False),
    sa.Column('segment', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('order_count >= 0', name='ck_customer_order_count_nonneg'),
    sa.CheckConstraint('return_count >= 0', name='ck_customer_return_count_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_city'), 'customers', ['city'], unique=False)
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_external_id'), 'customers', ['external_id'], unique=True)
    op.create_index(op.f('ix_customers_pincode'), 'customers', ['pincode'], unique=False)
    op.create_index(op.f('ix_customers_segment'), 'customers', ['segment'], unique=False)
    op.create_index('ix_customers_segment_city', 'customers', ['segment', 'city'], unique=False)
    op.create_index(op.f('ix_customers_signup_date'), 'customers', ['signup_date'], unique=False)
    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('artifact_path', sa.String(length=400), nullable=False),
    sa.Column('feature_names', sa.Text(), nullable=False),
    sa.Column('metrics', sa.Text(), nullable=False),
    sa.Column('training_rows', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_registry_created_at'), 'model_registry', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_registry_name'), 'model_registry', ['name'], unique=False)
    op.create_index(op.f('ix_model_registry_trained_at'), 'model_registry', ['trained_at'], unique=False)
    op.create_index(op.f('ix_model_registry_version'), 'model_registry', ['version'], unique=False)
    op.create_index('ix_registry_name_trained', 'model_registry', ['name', 'trained_at'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('subcategory', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('has_size_variants', sa.Boolean(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('avg_rating >= 0 AND avg_rating <= 5', name='ck_product_rating_range'),
    sa.CheckConstraint('price > 0', name='ck_product_price_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index('ix_products_category_price', 'products', ['category', 'price'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_subcategory'), 'products', ['subcategory'], unique=False)
    op.create_table('checkout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_ref', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cart_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_cart_ratio', sa.Float(), nullable=False),
    sa.Column('payment_attempts', sa.Integer(), nullable=False),
    sa.Column('payment_failed', sa.Boolean(), nullable=False),
    sa.Column('payment_method', sa.String(length=24), nullable=False),
    sa.Column('device_type', sa.String(length=16), nullable=False),
    sa.Column('session_duration_sec', sa.Integer(), nullable=False),
    sa.Column('checkout_stage', sa.String(length=24), nullable=False),
    sa.Column('coupon_applied', sa.Boolean(), nullable=False),
    sa.Column('coupon_failed', sa.Boolean(), nullable=False),
    sa.Column('address_edits', sa.Integer(), nullable=False),
    sa.Column('page_errors', sa.Integer(), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('prior_order_count', sa.Integer(), nullable=False),
    sa.Column('prior_abandonment_count', sa.Integer(), nullable=False),
    sa.Column('prior_return_count', sa.Integer(), nullable=False),
    sa.Column('prior_rto_count', sa.Integer(), nullable=False),
    sa.Column('abandoned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cart_value >= 0', name='ck_session_cart_value_nonneg'),
    sa.CheckConstraint('payment_attempts >= 0', name='ck_session_attempts_nonneg'),
    sa.CheckConstraint('shipping_cart_ratio >= 0', name='ck_session_ship_ratio_nonneg'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkout_sessions_abandoned'), 'checkout_sessions', ['abandoned'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_checkout_stage'), 'checkout_sessions', ['checkout_stage'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_created_at'), 'checkout_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_customer_id'), 'checkout_sessions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_device_type'), 'checkout_sessions', ['device_type'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_payment_method'), 'checkout_sessions', ['payment_method'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_session_ref'), 'checkout_sessions', ['session_ref'], unique=True)
    op.create_index(op.f('ix_checkout_sessions_started_at'), 'checkout_sessions', ['started_at'], unique=False)
    op.create_index('ix_sessions_abandoned_started', 'checkout_sessions', ['abandoned', 'started_at'], unique=False)
    op.create_index('ix_sessions_customer_started', 'checkout_sessions', ['customer_id', 'started_at'], unique=False)
    op.create_table('product_voc_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('negative_share', sa.Float(), nullable=False),
    sa.Column('size_fit_complaint_rate', sa.Float(), nullable=False),
    sa.Column('quality_complaint_rate', sa.Float(), nullable=False),
    sa.Column('delivery_complaint_rate', sa.Float(), nullable=False),
    sa.Column('packaging_complaint_rate', sa.Float(), nullable=False),
    sa.Column('support_complaint_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_fit_complaint_rate >= 0 AND size_fit_complaint_rate <= 1', name='ck_voc_sizefit_range'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_voc_signals_computed_at'), 'product_voc_signals', ['computed_at'], unique=False)
    op.create_index(op.f('ix_product_voc_signals_created_at'), 'product_voc_signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_voc_signals_product_id'), 'product_voc_signals', ['product_id'], unique=True)
    op.create_table('seller_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('aspect', sa.String(length=32), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=12), nullable=False),
    sa.Column('supporting_review_count', sa.Integer(), nullable=False),
    sa.Column('negative_share', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('estimated_business_impact', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('impact_basis', sa.Text(), nullable=True),
    sa.Column('linked_risk_signal', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recs_scope_priority', 'seller_recommendations', ['scope', 'priority'], unique=False)
    op.create_index(op.f('ix_seller_recommendations_aspect'), 'seller_recommendations', ['aspect'], unique=False)
    op.create_index(op.f('ix_seller_recommendations_category'), 'seller_recommendations', ['category'], unique=False)
    op.create_index(op.f('ix_seller_recommendations_created_at'), 'seller_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_seller_recommendations_generated_at'), 'seller_recommendations', ['generated_at'], unique=False)
    op.create_index(op.f('ix_seller_recommendations_linked_risk_signal'), 'seller_recommendations', ['linked_risk_signal'], unique=False)
    op.create_index(op.f('ix_seller_recommendations_priority'), 'seller_recommendations', ['priority'], unique=False)
    op.create_index(op.f('ix_seller_recommendations_product_id'), 'seller_recommendations', ['product_id'], unique=False)
    op.create_index(op.f('ix_seller_recommendations_scope'), 'seller_recommendations', ['scope'], unique=False)
    op.create_table('abandoned_carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkout_session_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('abandoned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cart_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('primary_reason', sa.String(length=32), nullable=True),
    sa.Column('reason_confidence', sa.Float(), nullable=True),
    sa.Column('reason_evidence', sa.Text(), nullable=True),
    sa.Column('recovered', sa.Boolean(), nullable=False),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovered_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checkout_session_id'], ['checkout_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abandoned_carts_abandoned_at'), 'abandoned_carts', ['abandoned_at'], unique=False)
    op.create_index(op.f('ix_abandoned_carts_checkout_session_id'), 'abandoned_carts', ['checkout_session_id'], unique=True)
    op.create_index(op.f('ix_abandoned_carts_created_at'), 'abandoned_carts', ['created_at'], unique=False)
    op.create_index(op.f('ix_abandoned_carts_customer_id'), 'abandoned_carts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_abandoned_carts_primary_reason'), 'abandoned_carts', ['primary_reason'], unique=False)
    op.create_index(op.f('ix_abandoned_carts_recovered'), 'abandoned_carts', ['recovered'], unique=False)
    op.create_index('ix_carts_reason_recovered', 'abandoned_carts', ['primary_reason', 'recovered'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_ref', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('checkout_session_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=24), nullable=False),
    sa.Column('is_cod', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('order_value >= 0', name='ck_order_value_nonneg'),
    sa.ForeignKeyConstraint(['checkout_session_id'], ['checkout_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_checkout_session_id'), 'orders', ['checkout_session_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_customer_date', 'orders', ['customer_id', 'order_date'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_is_cod'), 'orders', ['is_cod'], unique=False)
    op.create_index(op.f('ix_orders_order_date'), 'orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_orders_order_ref'), 'orders', ['order_ref'], unique=True)
    op.create_index(op.f('ix_orders_payment_method'), 'orders', ['payment_method'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abandoned_cart_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('pillar', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_probability', sa.Float(), nullable=False),
    sa.Column('expected_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('intervention_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('predicted_probability >= 0 AND predicted_probability <= 1', name='ck_intervention_prob_range'),
    sa.ForeignKeyConstraint(['abandoned_cart_id'], ['abandoned_carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_abandoned_cart_id'), 'interventions', ['abandoned_cart_id'], unique=False)
    op.create_index(op.f('ix_interventions_action'), 'interventions', ['action'], unique=False)
    op.create_index(op.f('ix_interventions_created_at'), 'interventions', ['created_at'], unique=False)
    op.create_index(op.f('ix_interventions_customer_id'), 'interventions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_interventions_order_id'), 'interventions', ['order_id'], unique=False)
    op.create_index(op.f('ix_interventions_outcome'), 'interventions', ['outcome'], unique=False)
    op.create_index(op.f('ix_interventions_pillar'), 'interventions', ['pillar'], unique=False)
    op.create_index('ix_interventions_pillar_action', 'interventions', ['pillar', 'action'], unique=False)
    op.create_index(op.f('ix_interventions_sent_at'), 'interventions', ['sent_at'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('selected_size', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_order_item_qty_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_created_at'), 'order_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_ref', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('checkout_session_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('failure_reason', sa.String(length=64), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_payment_amount_nonneg'),
    sa.ForeignKeyConstraint(['checkout_session_id'], ['checkout_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_attempted_at'), 'payments', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_payments_checkout_session_id'), 'payments', ['checkout_session_id'], unique=False)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_failure_reason'), 'payments', ['failure_reason'], unique=False)
    op.create_index(op.f('ix_payments_method'), 'payments', ['method'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_ref'), 'payments', ['payment_ref'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index('ix_payments_status_method', 'payments', ['status', 'method'], unique=False)
    op.create_table('return_risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('return_probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=12), nullable=False),
    sa.Column('top_factors', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.String(length=40), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('return_probability >= 0 AND return_probability <= 1', name='ck_return_score_range'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_risk_scores_created_at'), 'return_risk_scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_return_risk_scores_customer_id'), 'return_risk_scores', ['customer_id'], unique=False)
    op.create_index(op.f('ix_return_risk_scores_order_id'), 'return_risk_scores', ['order_id'], unique=False)
    op.create_index(op.f('ix_return_risk_scores_product_id'), 'return_risk_scores', ['product_id'], unique=False)
    op.create_index(op.f('ix_return_risk_scores_risk_level'), 'return_risk_scores', ['risk_level'], unique=False)
    op.create_index(op.f('ix_return_risk_scores_scored_at'), 'return_risk_scores', ['scored_at'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_ref', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_customer_id'), 'reviews', ['customer_id'], unique=False)
    op.create_index(op.f('ix_reviews_order_id'), 'reviews', ['order_id'], unique=False)
    op.create_index('ix_reviews_product_date', 'reviews', ['product_id', 'review_date'], unique=False)
    op.create_index(op.f('ix_reviews_product_id'), 'reviews', ['product_id'], unique=False)
    op.create_index(op.f('ix_reviews_rating'), 'reviews', ['rating'], unique=False)
    op.create_index(op.f('ix_reviews_review_date'), 'reviews', ['review_date'], unique=False)
    op.create_index(op.f('ix_reviews_review_ref'), 'reviews', ['review_ref'], unique=True)
    op.create_index(op.f('ix_reviews_source'), 'reviews', ['source'], unique=False)
    op.create_table('rto_risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rto_probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=12), nullable=False),
    sa.Column('top_factors', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.String(length=40), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rto_probability >= 0 AND rto_probability <= 1', name='ck_rto_score_range'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rto_risk_scores_created_at'), 'rto_risk_scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_rto_risk_scores_customer_id'), 'rto_risk_scores', ['customer_id'], unique=False)
    op.create_index(op.f('ix_rto_risk_scores_order_id'), 'rto_risk_scores', ['order_id'], unique=False)
    op.create_index(op.f('ix_rto_risk_scores_risk_level'), 'rto_risk_scores', ['risk_level'], unique=False)
    op.create_index(op.f('ix_rto_risk_scores_scored_at'), 'rto_risk_scores', ['scored_at'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('awb', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('courier', sa.String(length=48), nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promised_days', sa.Integer(), nullable=False),
    sa.Column('actual_days', sa.Integer(), nullable=True),
    sa.Column('delivery_attempts', sa.Integer(), nullable=False),
    sa.Column('declared_weight_kg', sa.Float(), nullable=False),
    sa.Column('measured_weight_kg', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_rto', sa.Boolean(), nullable=False),
    sa.Column('rto_reason', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('delivery_attempts >= 0', name='ck_shipment_attempts_nonneg'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_awb'), 'shipments', ['awb'], unique=True)
    op.create_index(op.f('ix_shipments_courier'), 'shipments', ['courier'], unique=False)
    op.create_index('ix_shipments_courier_status', 'shipments', ['courier', 'status'], unique=False)
    op.create_index(op.f('ix_shipments_created_at'), 'shipments', ['created_at'], unique=False)
    op.create_index(op.f('ix_shipments_customer_id'), 'shipments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_shipments_is_rto'), 'shipments', ['is_rto'], unique=False)
    op.create_index(op.f('ix_shipments_order_id'), 'shipments', ['order_id'], unique=False)
    op.create_index(op.f('ix_shipments_rto_reason'), 'shipments', ['rto_reason'], unique=False)
    op.create_index(op.f('ix_shipments_shipped_at'), 'shipments', ['shipped_at'], unique=False)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_table('conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('realised_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('realised_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversions_converted_at'), 'conversions', ['converted_at'], unique=False)
    op.create_index(op.f('ix_conversions_created_at'), 'conversions', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversions_customer_id'), 'conversions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_conversions_intervention_id'), 'conversions', ['intervention_id'], unique=True)
    op.create_index(op.f('ix_conversions_order_id'), 'conversions', ['order_id'], unique=False)
    op.create_table('customer_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('aspect', sa.String(length=32), nullable=False),
    sa.Column('suggestion_text', sa.Text(), nullable=False),
    sa.Column('normalized_suggestion', sa.String(length=120), nullable=False),
    sa.Column('source_span', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_suggestions_aspect'), 'customer_suggestions', ['aspect'], unique=False)
    op.create_index(op.f('ix_customer_suggestions_created_at'), 'customer_suggestions', ['created_at'], unique=False)
    op.create_index(op.f('ix_customer_suggestions_normalized_suggestion'), 'customer_suggestions', ['normalized_suggestion'], unique=False)
    op.create_index(op.f('ix_customer_suggestions_product_id'), 'customer_suggestions', ['product_id'], unique=False)
    op.create_index(op.f('ix_customer_suggestions_review_id'), 'customer_suggestions', ['review_id'], unique=False)
    op.create_index('ix_suggestions_norm_aspect', 'customer_suggestions', ['normalized_suggestion', 'aspect'], unique=False)
    op.create_table('fraud_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('anomaly_class', sa.String(length=32), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=12), nullable=False),
    sa.Column('triggered_rules', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.String(length=40), nullable=True),
    sa.Column('estimated_exposure', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fraud_class_level', 'fraud_events', ['anomaly_class', 'risk_level'], unique=False)
    op.create_index(op.f('ix_fraud_events_anomaly_class'), 'fraud_events', ['anomaly_class'], unique=False)
    op.create_index(op.f('ix_fraud_events_created_at'), 'fraud_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_fraud_events_customer_id'), 'fraud_events', ['customer_id'], unique=False)
    op.create_index(op.f('ix_fraud_events_detected_at'), 'fraud_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_fraud_events_order_id'), 'fraud_events', ['order_id'], unique=False)
    op.create_index(op.f('ix_fraud_events_risk_level'), 'fraud_events', ['risk_level'], unique=False)
    op.create_index(op.f('ix_fraud_events_shipment_id'), 'fraud_events', ['shipment_id'], unique=False)
    op.create_table('logistics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('detail', sa.String(length=240), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_shipment_type', 'logistics_events', ['shipment_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_logistics_events_created_at'), 'logistics_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_logistics_events_event_at'), 'logistics_events', ['event_at'], unique=False)
    op.create_index(op.f('ix_logistics_events_event_type'), 'logistics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_logistics_events_shipment_id'), 'logistics_events', ['shipment_id'], unique=False)
    op.create_table('returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_ref', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('refund_amount >= 0', name='ck_return_refund_nonneg'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_returns_created_at'), 'returns', ['created_at'], unique=False)
    op.create_index(op.f('ix_returns_customer_id'), 'returns', ['customer_id'], unique=False)
    op.create_index(op.f('ix_returns_order_id'), 'returns', ['order_id'], unique=False)
    op.create_index(op.f('ix_returns_order_item_id'), 'returns', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_returns_product_id'), 'returns', ['product_id'], unique=False)
    op.create_index('ix_returns_product_reason', 'returns', ['product_id', 'reason'], unique=False)
    op.create_index(op.f('ix_returns_reason'), 'returns', ['reason'], unique=False)
    op.create_index(op.f('ix_returns_requested_at'), 'returns', ['requested_at'], unique=False)
    op.create_index(op.f('ix_returns_return_ref'), 'returns', ['return_ref'], unique=True)
    op.create_index(op.f('ix_returns_status'), 'returns', ['status'], unique=False)
    op.create_table('review_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('sentiment', sa.String(length=12), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=12), nullable=False),
    sa.Column('business_impact', sa.Text(), nullable=True),
    sa.Column('topics', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_analysis_conf_range'),
    sa.CheckConstraint('sentiment_score >= -1 AND sentiment_score <= 1', name='ck_analysis_score_range'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_analysis_created_at'), 'review_analysis', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_analysis_language'), 'review_analysis', ['language'], unique=False)
    op.create_index(op.f('ix_review_analysis_priority'), 'review_analysis', ['priority'], unique=False)
    op.create_index(op.f('ix_review_analysis_review_id'), 'review_analysis', ['review_id'], unique=True)
    op.create_index(op.f('ix_review_analysis_sentiment'), 'review_analysis', ['sentiment'], unique=False)
    op.create_table('review_aspects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('aspect', sa.String(length=32), nullable=False),
    sa.Column('sentiment', sa.String(length=12), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('evidence_span', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'aspect', name='uq_review_aspect')
    )
    op.create_index('ix_aspects_aspect_sentiment', 'review_aspects', ['aspect', 'sentiment'], unique=False)
    op.create_index('ix_aspects_product_aspect', 'review_aspects', ['product_id', 'aspect'], unique=False)
    op.create_index(op.f('ix_review_aspects_aspect'), 'review_aspects', ['aspect'], unique=False)
    op.create_index(op.f('ix_review_aspects_created_at'), 'review_aspects', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_aspects_product_id'), 'review_aspects', ['product_id'], unique=False)
    op.create_index(op.f('ix_review_aspects_review_id'), 'review_aspects', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_aspects_sentiment'), 'review_aspects', ['sentiment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_aspects_sentiment'), table_name='review_aspects')
    op.drop_index(op.f('ix_review_aspects_review_id'), table_name='review_aspects')
    op.drop_index(op.f('ix_review_aspects_product_id'), table_name='review_aspects')
    op.drop_index(op.f('ix_review_aspects_created_at'), table_name='review_aspects')
    op.drop_index(op.f('ix_review_aspects_aspect'), table_name='review_aspects')
    op.drop_index('ix_aspects_product_aspect', table_name='review_aspects')
    op.drop_index('ix_aspects_aspect_sentiment', table_name='review_aspects')
    op.drop_table('review_aspects')
    op.drop_index(op.f('ix_review_analysis_sentiment'), table_name='review_analysis')
    op.drop_index(op.f('ix_review_analysis_review_id'), table_name='review_analysis')
    op.drop_index(op.f('ix_review_analysis_priority'), table_name='review_analysis')
    op.drop_index(op.f('ix_review_analysis_language'), table_name='review_analysis')
    op.drop_index(op.f('ix_review_analysis_created_at'), table_name='review_analysis')
    op.drop_table('review_analysis')
    op.drop_index(op.f('ix_returns_status'), table_name='returns')
    op.drop_index(op.f('ix_returns_return_ref'), table_name='returns')
    op.drop_index(op.f('ix_returns_requested_at'), table_name='returns')
    op.drop_index(op.f('ix_returns_reason'), table_name='returns')
    op.drop_index('ix_returns_product_reason', table_name='returns')
    op.drop_index(op.f('ix_returns_product_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_order_item_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_order_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_customer_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_created_at'), table_name='returns')
    op.drop_table('returns')
    op.drop_index(op.f('ix_logistics_events_shipment_id'), table_name='logistics_events')
    op.drop_index(op.f('ix_logistics_events_event_type'), table_name='logistics_events')
    op.drop_index(op.f('ix_logistics_events_event_at'), table_name='logistics_events')
    op.drop_index(op.f('ix_logistics_events_created_at'), table_name='logistics_events')
    op.drop_index('ix_events_shipment_type', table_name='logistics_events')
    op.drop_table('logistics_events')
    op.drop_index(op.f('ix_fraud_events_shipment_id'), table_name='fraud_events')
    op.drop_index(op.f('ix_fraud_events_risk_level'), table_name='fraud_events')
    op.drop_index(op.f('ix_fraud_events_order_id'), table_name='fraud_events')
    op.drop_index(op.f('ix_fraud_events_detected_at'), table_name='fraud_events')
    op.drop_index(op.f('ix_fraud_events_customer_id'), table_name='fraud_events')
    op.drop_index(op.f('ix_fraud_events_created_at'), table_name='fraud_events')
    op.drop_index(op.f('ix_fraud_events_anomaly_class'), table_name='fraud_events')
    op.drop_index('ix_fraud_class_level', table_name='fraud_events')
    op.drop_table('fraud_events')
    op.drop_index('ix_suggestions_norm_aspect', table_name='customer_suggestions')
    op.drop_index(op.f('ix_customer_suggestions_review_id'), table_name='customer_suggestions')
    op.drop_index(op.f('ix_customer_suggestions_product_id'), table_name='customer_suggestions')
    op.drop_index(op.f('ix_customer_suggestions_normalized_suggestion'), table_name='customer_suggestions')
    op.drop_index(op.f('ix_customer_suggestions_created_at'), table_name='customer_suggestions')
    op.drop_index(op.f('ix_customer_suggestions_aspect'), table_name='customer_suggestions')
    op.drop_table('customer_suggestions')
    op.drop_index(op.f('ix_conversions_order_id'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_intervention_id'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_customer_id'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_created_at'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_converted_at'), table_name='conversions')
    op.drop_table('conversions')
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_shipped_at'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_rto_reason'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_order_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_is_rto'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_customer_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_created_at'), table_name='shipments')
    op.drop_index('ix_shipments_courier_status', table_name='shipments')
    op.drop_index(op.f('ix_shipments_courier'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_awb'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_rto_risk_scores_scored_at'), table_name='rto_risk_scores')
    op.drop_index(op.f('ix_rto_risk_scores_risk_level'), table_name='rto_risk_scores')
    op.drop_index(op.f('ix_rto_risk_scores_order_id'), table_name='rto_risk_scores')
    op.drop_index(op.f('ix_rto_risk_scores_customer_id'), table_name='rto_risk_scores')
    op.drop_index(op.f('ix_rto_risk_scores_created_at'), table_name='rto_risk_scores')
    op.drop_table('rto_risk_scores')
    op.drop_index(op.f('ix_reviews_source'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_review_ref'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_review_date'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_rating'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_product_id'), table_name='reviews')
    op.drop_index('ix_reviews_product_date', table_name='reviews')
    op.drop_index(op.f('ix_reviews_order_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_customer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_return_risk_scores_scored_at'), table_name='return_risk_scores')
    op.drop_index(op.f('ix_return_risk_scores_risk_level'), table_name='return_risk_scores')
    op.drop_index(op.f('ix_return_risk_scores_product_id'), table_name='return_risk_scores')
    op.drop_index(op.f('ix_return_risk_scores_order_id'), table_name='return_risk_scores')
    op.drop_index(op.f('ix_return_risk_scores_customer_id'), table_name='return_risk_scores')
    op.drop_index(op.f('ix_return_risk_scores_created_at'), table_name='return_risk_scores')
    op.drop_table('return_risk_scores')
    op.drop_index('ix_payments_status_method', table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_ref'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_method'), table_name='payments')
    op.drop_index(op.f('ix_payments_failure_reason'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_checkout_session_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_attempted_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_created_at'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_interventions_sent_at'), table_name='interventions')
    op.drop_index('ix_interventions_pillar_action', table_name='interventions')
    op.drop_index(op.f('ix_interventions_pillar'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_outcome'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_order_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_customer_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_created_at'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_action'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_abandoned_cart_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_method'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_ref'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_date'), table_name='orders')
    op.drop_index(op.f('ix_orders_is_cod'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index('ix_orders_customer_date', table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_checkout_session_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_carts_reason_recovered', table_name='abandoned_carts')
    op.drop_index(op.f('ix_abandoned_carts_recovered'), table_name='abandoned_carts')
    op.drop_index(op.f('ix_abandoned_carts_primary_reason'), table_name='abandoned_carts')
    op.drop_index(op.f('ix_abandoned_carts_customer_id'), table_name='abandoned_carts')
    op.drop_index(op.f('ix_abandoned_carts_created_at'), table_name='abandoned_carts')
    op.drop_index(op.f('ix_abandoned_carts_checkout_session_id'), table_name='abandoned_carts')
    op.drop_index(op.f('ix_abandoned_carts_abandoned_at'), table_name='abandoned_carts')
    op.drop_table('abandoned_carts')
    op.drop_index(op.f('ix_seller_recommendations_scope'), table_name='seller_recommendations')
    op.drop_index(op.f('ix_seller_recommendations_product_id'), table_name='seller_recommendations')
    op.drop_index(op.f('ix_seller_recommendations_priority'), table_name='seller_recommendations')
    op.drop_index(op.f('ix_seller_recommendations_linked_risk_signal'), table_name='seller_recommendations')
    op.drop_index(op.f('ix_seller_recommendations_generated_at'), table_name='seller_recommendations')
    op.drop_index(op.f('ix_seller_recommendations_created_at'), table_name='seller_recommendations')
    op.drop_index(op.f('ix_seller_recommendations_category'), table_name='seller_recommendations')
    op.drop_index(op.f('ix_seller_recommendations_aspect'), table_name='seller_recommendations')
    op.drop_index('ix_recs_scope_priority', table_name='seller_recommendations')
    op.drop_table('seller_recommendations')
    op.drop_index(op.f('ix_product_voc_signals_product_id'), table_name='product_voc_signals')
    op.drop_index(op.f('ix_product_voc_signals_created_at'), table_name='product_voc_signals')
    op.drop_index(op.f('ix_product_voc_signals_computed_at'), table_name='product_voc_signals')
    op.drop_table('product_voc_signals')
    op.drop_index('ix_sessions_customer_started', table_name='checkout_sessions')
    op.drop_index('ix_sessions_abandoned_started', table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_started_at'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_session_ref'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_payment_method'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_device_type'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_customer_id'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_created_at'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_checkout_stage'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_abandoned'), table_name='checkout_sessions')
    op.drop_table('checkout_sessions')
    op.drop_index(op.f('ix_products_subcategory'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index('ix_products_category_price', table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index('ix_registry_name_trained', table_name='model_registry')
    op.drop_index(op.f('ix_model_registry_version'), table_name='model_registry')
    op.drop_index(op.f('ix_model_registry_trained_at'), table_name='model_registry')
    op.drop_index(op.f('ix_model_registry_name'), table_name='model_registry')
    op.drop_index(op.f('ix_model_registry_created_at'), table_name='model_registry')
    op.drop_table('model_registry')
    op.drop_index(op.f('ix_customers_signup_date'), table_name='customers')
    op.drop_index('ix_customers_segment_city', table_name='customers')
    op.drop_index(op.f('ix_customers_segment'), table_name='customers')
    op.drop_index(op.f('ix_customers_pincode'), table_name='customers')
    op.drop_index(op.f('ix_customers_external_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.drop_index(op.f('ix_customers_city'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
